### ISSUE TITLE
IOS 11.1.1 update fails to display, no errors

### ISSUE THREAD

**Issue by TomWhiteCSL** [skwasjer/skwas-cordova-plugin-datetimepicker#15]
Previously was working beautifully - using Angular inside Cordova...

(<any>window).cordova.plugins.DateTimePicker.show({
        mode: 'datetime',
        date: myDate,
        allowOldDates: true,
        allowFutureDates: true,
        minuteInterval: 15,
        locale: 'EN',
        okText: 'Select',
        cancelText: 'Cancel',
        android: {
          theme: 16974126, // Theme_DeviceDefault_Dialog
          calendar: true,
          is24HourView: true
        },
        success: function(newDate) {...

Since IOS update, now fails silently.

**Comment by skwasjer** [comment]
I am running 11.1 and it seems to be working for me. Are there any other dependencies that have been updated in your app (cordova, other plugins)?

Try to set a breakpoint in:
https://github.com/skwasjer/skwas-cordova-plugin-datetimepicker/blob/master/src/ios/DateTimePicker.m#L31

and debug from there. If it hits at least the plugin is still getting called.

**Comment by TomWhiteCSL** [comment]
Hello skwasjer
Thanks for your prompt reply. I have been thinking about this over the weekend and come to the same conclusion as you. Thanks for confirming you've tested with IOS 11.1
I'm wading through build chain update issues at the moment - any one of which may be causing the problem. I'll confirm when I solve it.
Kind regards
Tom
