### ISSUE TITLE
cancel callback not executed on android

### ISSUE THREAD

**Issue by budi7** [skwasjer/skwas-cordova-plugin-datetimepicker#18]
hi, 
i found that this plugin are amazing, but unfortunately i have some problem with the cancel callback. my code block on cancel never get executed, instead the success callback are called. This problem only occured on "date" mode, and works good on mode "time"

here's my code

 cordova.plugins.DateTimePicker.show({
            mode: "date",
            date: myDate,
            allowOldDates: true,
            allowFutureDates: false,
            minuteInterval: 1,
            locale: "EN",
            okText: "Ok",
            cancelText: "Cancel",
            android: {
                theme: 16974126, // Theme_DeviceDefault_Dialog
                calendar: false,
                is24HourView: false
            },
            success: function (newDate) {
                var rslt = newDate.getDate() + '/' + (newDate.getMonth() + 1) + '/' + newDate.getFullYear() + " ";
                target.val(rslt);
                myDate = newDate;
            },
            cancel: function () {
                // just do nothing 
                alert("cancel"); // it's not called
            },
            error: function (err) {
                alert("error");
            }
        });

**Comment by budi7** [comment]
and, FYI, i'm doing this test on android emulator runs 4.2

**Comment by skwasjer** [comment]
Could you try debugging yourself and possibly provide a PR? I am currently unable to troubleshoot this issue, since I am working on other projects. If not, please be patient and I will have a look at it at some point in the future.

**Comment by skwasjer** [comment]
Released in v1.1.3
