### ISSUE TITLE
Crashing On IOS - Add support for min and max date

### ISSUE THREAD

**Issue by balachandranmca** [skwasjer/skwas-cordova-plugin-datetimepicker#22]
cordova.plugins.DateTimePicker.show({
   maxDate: null,
})

src/ios/DateTimePicker.m
 long long maxDate = [[optionsOrNil objectForKey:@"maxDate"] longLongValue];

The above line is causing an exception for converting null value to longLongValue.

**Comment by skwasjer** [comment]
#20 

Thanks for the report.

I can't check it myself right now, but it should probably just take some small refactoring and usage of NSNumber instead of long long to support nullables.

**Comment by balachandranmca** [comment]
Ok

**Comment by skwasjer** [comment]
Actual fix in 2dc7b7cc9d8d918cbe6438b0d861c8308a0744ed
