### ISSUE TITLE
IOS DatePicker Cancel Button Problem

### ISSUE THREAD

**Issue by balachandranmca** [skwasjer/skwas-cordova-plugin-datetimepicker#23]
In IOS Mobile, if you click DatePicker then you click cancel button and again you click DatePicker default date is change to January month

**Comment by skwasjer** [comment]
Can you attach some sample code illustrating the problem? Also, which iOS version?

**Comment by balachandranmca** [comment]
IOS 10

**Comment by skwasjer** [comment]
Unable to reproduce, closing due to lack of context provided. @balachandranmca if you can be more specific and provide example code that illustrates the problem, I am willing to look into it again

**Comment by jeganwbc** [comment]
**First Time Click the Datepicker**
![](https://lh3.googleusercontent.com/-G-OChf0mm5w/XXjG9eFwJyI/AAAAAAAAC1M/MVtSbLXhO9YLcJl7oMVTvdarVij1JFZUQCK8BGAsYHg/s0/2019-09-11.jpg)

**Then cancel and open datepicker**
![](https://lh3.googleusercontent.com/-mY8IQ-iQ78o/XXjG8WBKk5I/AAAAAAAAC1I/ngNoa0XgVM8Wjh3kzjfEi5ZM6ADndNQ8QCK8BGAsYHg/s0/2019-09-11.jpg)
