### ISSUE TITLE
App crashes when passing a date instantiated with time in the PM

### ISSUE THREAD

**Issue by nshoes** [skwasjer/skwas-cordova-plugin-datetimepicker#27]
My use case is setting a time range of `n` hours, and the start time starts at the next hour. The end range needs to respect the current meridian, e.g. it's 8:15AM so the display would show 9AM - 1PM. Trying to set `13:00` on a JavaScript date works, but when passed to `options.date`, my app crashes. How can I help debug this further?

**Comment by nshoes** [comment]
Oops! Seems that I was trimming some option that said had defaults in the readme but crashed the app when they were omitted. Everything is good now 👌

**Comment by skwasjer** [comment]
Ye defaults not working is a known issue with current release (#24). This is fixed on the develop branch but has some other pending stuff I haven't gotten around too. Good you figured it out!
