### ISSUE TITLE
How do I get the time I have selected ?

### ISSUE THREAD

**Issue by shreyasb0912** [skwasjer/skwas-cordova-plugin-datetimepicker#30]
Hi,

I am using mode = "time" keeping the return value as it is i.e Date.

I want to get the time selected from the picker but it is throwing some error when I convert the date that is returned, into time data type.

Can anyone please me know how do I achieve to get the time selected from picker.

Regards,
Shreyas Bhondve

**Comment by skwasjer** [comment]
The plugin always requires a `Date` object to start with and returns a `Date` object in the success callback, even in `time` mode. Generally, if you use the time mode, and only want the time component, you will have to subtract the 'today' date component:

```
var now = new Date();
var today = new Date(now.getFullYear(), now.getMonth(), now.getDate());

cordova.plugins.DateTimePicker.show({
    mode: "time",
    date: now,
    ... other options ...
    success: function(newDate) {
        var timeInMillisecs = newDate.valueOf() - today.valueOf();
    }
});
```
