### ISSUE TITLE
IOS Cancel Button Clicks Date Resets to Jan 1

### ISSUE THREAD

**Issue by jeganwbc** [skwasjer/skwas-cordova-plugin-datetimepicker#33]
**First Time Click the Datepicker**
![](https://lh3.googleusercontent.com/-G-OChf0mm5w/XXjG9eFwJyI/AAAAAAAAC1M/MVtSbLXhO9YLcJl7oMVTvdarVij1JFZUQCK8BGAsYHg/s0/2019-09-11.jpg)

**Then cancel and open datepicker**
![](https://lh3.googleusercontent.com/-mY8IQ-iQ78o/XXjG8WBKk5I/AAAAAAAAC1I/ngNoa0XgVM8Wjh3kzjfEi5ZM6ADndNQ8QCK8BGAsYHg/s0/2019-09-11.jpg)

**Comment by skwasjer** [comment]
Can you provide sample code and ? I cannot reproduce this.

**Comment by jeganwbc** [comment]
cordova.plugins.DateTimePicker.show({
            mode: "datetime",
            date: new Date(),
            allowOldDates: false,
            allowFutureDates: true,
            minDate: new Date(),
            maxDate: null,
            locale: "EN",
            minuteInterval: min_interval,
            okText: ok_text,
            cancelText: cancel_text,
            android: {
                theme: 16974126, // Theme_DeviceDefault_Dialog
                is24HourView: false
            },
            success: function (newDate) {
                     //success event
            },
            cancel: function () {
                //cancel event
            },
            error: function (err) {
                console.error(err);
            }
        });

**Comment by skwasjer** [comment]
Found the issue, it is happening icw. minute interval > 1. I'll push a fix.

**Comment by jeganwbc** [comment]
ok..! I am waiting..!

**Comment by skwasjer** [comment]
A fix (and some other refactoring) has been done on `develop` branch. You can verify if it works by removing the plugin and reinstalling directly from git:

```
cordova plugin add https://github.com/skwasjer/skwas-cordova-plugin-datetimepicker.git#develop
```

If this works well, I will push an update to NPM

**Comment by jeganwbc** [comment]
Working fine..! push an update to NPM.
