### ISSUE TITLE
iOS in dark mode, time spinner font white

### ISSUE THREAD

**Issue by fabriziovirdis1** [skwasjer/skwas-cordova-plugin-datetimepicker#35]
In iOS with dark mode enabled the time font of spinner is white and cannot see selected time.

**Comment by skwasjer** [comment]
This will take some time, I have a very old mini that needs upgrading first to test with higher iOS versions. But some code is already being redesigned (non-related to this) to utilize `UINavigationBar`, so I'm hoping that might fix it regardless (not sure yet).
