### ISSUE TITLE
Phonegap Build - iOS issue

### ISSUE THREAD

**Issue by netzzeit** [skwasjer/skwas-cordova-plugin-datetimepicker#39]
**Describe the bug**
When using PGB I get a Build-Error for iOS. In the error log it says:

_In file included from /project/myApp/Plugins/skwas-cordova-plugin-datetimepicker/ModalPickerViewController.m:1:
/project/myApp/Plugins/skwas-cordova-plugin-datetimepicker/ModalPickerViewController.h:14:52: warning: this block declaration is not a prototype [-Wstrict-prototypes]
@property (nonatomic, strong) void (^cancelHandler)();
                                                   ^
                                                    void
/project/myApp/Plugins/skwas-cordova-plugin-datetimepicker/ModalPickerViewController.m:182:42: error: no known class method for selector 'linkColor'
        lightButtonLabelColor = [UIColor linkColor];
                                         ^~~~~~~~~
/project/myApp/Plugins/skwas-cordova-plugin-datetimepicker/ModalPickerViewController.m:183:41: error: no known class method for selector 'labelColor'
        darkButtonLabelColor = [UIColor labelColor];
                                        ^~~~~~~~~~
/project/myApp/Plugins/skwas-cordova-plugin-datetimepicker/ModalPickerViewController.m:185:42: error: no known class method for selector 'systemBlueColor'
        lightButtonLabelColor = [UIColor systemBlueColor];
                                         ^~~~~~~~~~~~~~~
1 warning and 3 errors generated._

The final message is:

_The following build commands failed:
	CompileC /Library/Developer/Xcode/DerivedData/myApp-bmmughqmovduvjaubxzkotytxccb/Build/Intermediates.noindex/ArchiveIntermediates/myApp/IntermediateBuildFilesPath/myApp.build/Release-iphoneos/myApp.build/Objects-normal/armv7/ModalPickerViewController.o myApp/Plugins/skwas-cordova-plugin-datetimepicker/ModalPickerViewController.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Error: xcodebuild: Command failed with exit code 65
    at ChildProcess.whenDone (/private/project/cordova/node_modules/cordova-common/src/superspawn.js:135:23)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)_

**To Reproduce**
Include Plugin in iOS-Project and hit Build.

**Cordova**
List Cordova versions by running:
- PGB / cli-9.0.0 (5.0.1 / 8.0.0 / 7.0.0)

**Plugin version**
Tested with 2.1.1

**Development OS (please complete the following information):**
 - OS: Mac

**Additional context**
About a month ago the error was not present - using the same components listed above

**Comment by netzzeit** [comment]
You can propably close this issue. The error jumps to another plugin if I disable the plugin. :/

**Comment by skwasjer** [comment]
I can say that this is likely due to the newer Xcode version requirement, which I forgot to document. I have added dark mode support since v2.1.0 onwards, and while this is backward compatible to older iOS versions (9.0), it does require Xcode 11 to build. It may also be the reason for the other plugin to fail (if it depends on newer iOS SDK/Xcode). Is there any way possible you can test with Xcode 11?

I may investigate if it is possible to lower this requirement, however, I strongly recommend upgrading regardless. At any rate, you could use plugin version v2.0.1 with older Xcode versions, but will miss out on the newer features, fixes and improvements.

As far as the one warning, this I can actually fix and will do so soon.

**Comment by netzzeit** [comment]
Hey skwasjer, 

thank you for your quick reply. :) 

Unfortunately (and as far as I know) I cannot test it with Xcode 11 since I'm using PhoneGap Build. I guess I have to stick with version 2.0.1 as long as PGB doesn't update their service. For now I've downgraded your plugin and the other one to get a successful build.

Thank you for your excellent work and this awesome plugin! :)

**Comment by skwasjer** [comment]
Hopefully Xcode 11 gets added soon then to PGB. I will leave the issue open until I fix the warning for reference sake and already updated the readme with build requirements.

**Comment by skwasjer** [comment]
PGB is discontinued unfortunately so closing.

> Adobe has discontinued PhoneGap Build and ended investment in PhoneGap and Apache Cordova. This website is no longer being updated. Find out more details [here](https://blog.phonegap.com/update-for-customers-using-phonegap-and-phonegap-build-cc701c77502c)

https://build.phonegap.com/changelog
