### ISSUE TITLE
iOS - maxDate bug

### ISSUE THREAD

**Issue by yjseo29** [skwasjer/skwas-cordova-plugin-datetimepicker#40]
**Describe the bug**
Select time of last date set by maxDate does not work.

**To Reproduce**
Set mode to datetime.
minDate, maxDate Sets the date.
Time Picker for Last Date Does Not Work
* It works fine on Android.

**Cordova**
- cordova 9.0.0

**Plugin version**
2.1.1

**Development OS (please complete the following information):**
 - OS: [Windows, Mac]

**Device (please complete the following information):**
 - Device: [iPhoneXs]
 - OS: [iOS 13.2]

**Comment by skwasjer** [comment]
- Which locale/region the device is operating in?
- Can you provide a simplified code example reproducing the problem?

**Comment by yjseo29** [comment]
Sorry for the late reply
This is a mistake in my code.
When setting the minDate / maxDate values, you must also set the time.
I'm using the Moment.js library and I solved it with:

var minDate = moment("2019-12-01").toDate();
var maxDate = moment("2019-12-04").toDate();

edit:

var minDate = moment("2019-12-01").startOf("day").toDate();
var maxDate = moment("2019-12-04").endOf("day").toDate();

Thank you for providing a good plugin.
