### ISSUE TITLE
Time Display mode shows entire date, not just time -  iOS

### ISSUE THREAD

**Issue by macsupport** [skwasjer/skwas-cordova-plugin-datetimepicker#42]
**Describe the bug**
With display mode set to Time, full date and time show

**To Reproduce**
Set mode to Time
**Expected behavior**
Only Time should show

**Screenshots**

<img width="185" alt="Screen Shot 2020-01-28 at 2 37 07 PM" src="https://user-images.githubusercontent.com/624656/73312735-50a8b400-41de-11ea-99e0-45f205579e69.png">
Here is my Code:
              $(document).on('click', '.timepicker', function(event) {
              $(this).each(function(index) {
        	var now = new Date();
               var today = new Date(now.getFullYear(), now.getMonth(), now.getDate());
                var currentField = $(this);
                var myNewDate = Date.parse(currentField.val()) || new Date();

                // Same handling for iPhone and Android
                cordova.plugins.DateTimePicker.show({
                mode: "time",
                date: now,
                allowOldDates: true,
                allowFutureDates: true,
                minDate: null,
                maxDate: null,
                minuteInterval: 15,
                locale: "EN",
                okText: "Select",
                cancelText: "Cancel",
                android: {
                    theme:16974126, // Theme_DeviceDefault_Dialog
                    is24HourView: true
                },
                success: function(returnDate) {
                    var newDate = new Date(returnDate);
                    currentField.val(newDate.toString("HH:mm"));

                    // This fixes the problem you mention at the bottom of this script with it not working a second/third time around, because it is in focus.
                    currentField.blur();
                },
                

cancel: function() {
                    console.info("Cancelled");
                },
                error: function(err) {
                    // Handle error.
                    console.error(err);
                }
            });
          });
          });

**Cordova**
List Cordova versions by running:
- `cordova -v 9`
- `cordova platform iOS v5.1.1`

**Plugin version**
Current

**Development OS (please complete the following information):**
 - OS: [iOS]

**Device (please complete the following information):**
 - Device: [iPhone X]
 - OS: [13.3]

**Comment by skwasjer** [comment]
It is not a bug and not related to the plugin, it is merely a limitation of Javascript. The [`Date.prototype.toString`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toString) method has no `format` argument, thus this line will not work as you expect and instead return the `Date` object formatted as a complete datetime string:

```
currentField.val(newDate.toString("HH:mm"));
```

This sets the field to something like `Wed Jan 29 2020 17:04:21 GMT+0100 (Central European Standard Time`. Simply put, the format string is ignored. Here's a fiddle showcasing it does not work and some other variants you could potentially use.
https://jsfiddle.net/jur8oyqs/

Alternatively, you could use a polyfill like `DateJS` that replaces `toString()` with `toString(format)` if you want to use custom formatting https://github.com/abritinthebay/datejs/wiki/Format-Specifiers
