### ISSUE TITLE
Fullscreen stretched option

### ISSUE THREAD

**Issue by monove** [skwasjer/skwas-cordova-plugin-datetimepicker#43]
What would I need to change to make the actual datepicker stretch? I don't mean the dialog background, I mean to scale the entire dialog to have larger numbers etc.

**Comment by skwasjer** [comment]
For Android, you can change font size with theming:

https://github.com/skwasjer/skwas-cordova-plugin-datetimepicker/blob/master/docs/Android_custom_theme_and_styling.md
https://stackoverflow.com/questions/11727707/how-to-change-textsize-in-datepicker

For iOS, there currently is no way to change the text size. The plugin just uses operating system font sizes. Changing text size in the device appearance settings should change the size however I believe, but it is device specific.
