### ISSUE TITLE
[iOS] inferior UX since iOS 14

### ISSUE THREAD

**Issue by nijakobius** [skwasjer/skwas-cordova-plugin-datetimepicker#47]
Since iOS 14, the design of the iOS picker has changed to an imho inferior UX. It adds another two clicks to the process.

It used to be:
1. Swipe to change the time
2. Accept

![IMG_2275](https://user-images.githubusercontent.com/37240226/96575784-82642c80-12d1-11eb-9ccb-d45e3c624778.jpeg)

And now it's:
1. Click on time
2. Swipe to change the time (which is much more difficult, since the touchable area is significantly smaller)
3. Click to dismiss the calendar view
4. Accept

![IMG_2276](https://user-images.githubusercontent.com/37240226/96575851-9576fc80-12d1-11eb-8dc4-95738129a03a.jpeg)
![IMG_2277](https://user-images.githubusercontent.com/37240226/96575845-9445cf80-12d1-11eb-9f0a-dffa8634e85a.png)

Is there any chance we could go back to the old design or choose which one to use? :)

**My system**
iOS 14.0.1
skwas-cordova-plugin-datetimepicker 2.1.1
cordova -v 10.0.0
cordova ios 6.1.0

**Comment by skwasjer** [comment]
Hey, thanks for reporting. This has been addressed in https://github.com/skwasjer/skwas-cordova-plugin-datetimepicker/pull/45 👍
