### ISSUE TITLE
Feature Request - Year in Date/Time for ISO 14

### ISSUE THREAD

**Issue by aesculus** [skwasjer/skwas-cordova-plugin-datetimepicker#52]
This might just be a question vs a feature request.  Is there a way to have the year available when using the date/time picker under iSO 14x?  I get month, day and time, but I would also like the user to be able to select the year.

**Comment by skwasjer** [comment]
The plugin relies on `UIDatePicker` for iOS. I have not looked in depth at iOS SDK recently, but quick look I (still) don't think it is available out-of-the-box. Rewriting the picker to support this using custom controls would be a lot of work.

A workaround is to offer the user the option to first pick a date with `date` mode, followed (if OK'd) by a second choice using `time` mode (adjusted for the previous selected date). It's not great, but at least it's something and perhaps more explicit.

edit: I suppose looking into the compact calendar may be a possibility, but it's a bigger change too:
https://www.andyibanez.com/posts/new-uidatepicker-ios14/

**Comment by aesculus** [comment]
OK. Thanks for the tip. I was thinking around the same lines so I guess two minds must be correct. :-)

The year would not often be used so maybe even a pull down as an independent control just to change that would suffice.

I just did not want to do something extra when it was already provided.

Thanks for the help.
