### ISSUE TITLE
Date picker layout is not changing when orientation changes in android

### ISSUE THREAD

**Issue by prasad-renuka** [skwasjer/skwas-cordova-plugin-datetimepicker#55]
**Describe the bug**
A clear and concise description of what the bug is...

**To Reproduce**
Steps to reproduce the behavior...

**Expected behavior**
A clear and concise description of what you expected to happen...

**Screenshots**
If applicable, add screenshots to help explain your problem...

**Cordova**
List Cordova versions by running:
- `cordova -v`
- `cordova platform ls`

**Plugin version**
The version of this plugin...

**Development OS (please complete the following information):**
 - OS: [e.g. Windows, Mac]

**Device (please complete the following information):**
 - Device: [e.g. iPhone6, Samsung S4, Emulator]
 - OS: [e.g. iOS8.1, ..]

**Additional context**

**Comment by skwasjer** [comment]
Closing due to lack of information. Feel free to reopen and provide more information. I do prefer contributions as I don't actively work on Android/iOS projects currently.
