### ISSUE TITLE
On selecting current date ( example : ' Today 4 00 PM ') in IOS and closing the datepicker and opening it again we always get 'jan 1' selected ... 

### ISSUE THREAD

**Issue by sonakshichomal-kiwi** [skwasjer/skwas-cordova-plugin-datetimepicker#7]
![imgpsh_fullsize 1](https://cloud.githubusercontent.com/assets/20122700/23062632/8cb4cbf2-f52c-11e6-8d48-7fccd2f6f635.png)

**Comment by sonakshichomal-kiwi** [comment]
![imgpsh_fullsize 1](https://cloud.githubusercontent.com/assets/20122700/23062616/74aaacde-f52c-11e6-92a0-4e87d06d29e7.png)

**Comment by skwasjer** [comment]
Which iOS version? And can you provide some sample code how you call the plugin?

**Comment by sonakshichomal-kiwi** [comment]
HI

The issue is on all the versions of IOS..

Below is the code snippet :-1: 


validateDate.showDatePickerforCosult = function(scope,type,min,max){

    var options = { 
        mode: "datetime",
        date: (type == 'start'? scope.consultation_start_date.date : scope.consultation_end_date.date) ,
        allowOldDates: false,
        allowFutureDates: true,
        minuteInterval: 5,
        locale: "EN",
        okText: "Select",
        cancelText: "Cancel"
    };

    function onSuccess(date) {
       $timeout(function() { scope.$apply();});//added to improve rendering delay
        if(type == 'start'){
          scope.consultation_start_date = {
            displayDate: convertDate.toMMddYYYYInString(date),
            displayTime: convertDate.toAmPM(date),
            date:date

          }; 

        }else if(type == 'end'){
          scope.consultation_end_date = {
            displayDate: convertDate.toMMddYYYYInString(date),
            displayTime: convertDate.toAmPM(date),
            date:date

          };
        }        
    }

    function onError(error) { // Android only
        console.log('Error: ' + error);
    }

    cordova.plugins.DateTimePicker.show(options, onSuccess, onError);
   }

**Comment by skwasjer** [comment]
Since you are using angular, you should update your model in the $timeout. The success callback from the plugin runs outside angular's digest cycle, and thus your scope object is not updated until a digest cycle happens. Thus, reopening the picker will likely provide it with the old model value again, I think.

Also by wrapping it in the $timeout the scope.$apply you have currently then becomes unneeded.

We are using this plugin in ionic and angular apps ourselves and using this technique works fine.

```
function onSuccess(date) {
   $timeout(function() {
     if (type == 'start') {
       scope.consultation_start_date = {
         displayDate: convertDate.toMMddYYYYInString(date),
         displayTime: convertDate.toAmPM(date),
         date:date
       }; 
     } else if (type == 'end') {
       scope.consultation_end_date = {
         displayDate: convertDate.toMMddYYYYInString(date),
         displayTime: convertDate.toAmPM(date),
         date:date
       };
     }
   });
}
```
